### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by metainf** [bolderflight/mcu-support#1]
I've been working on setting up docker+cmake for my own project, and the cmake macros here have been a big help. Would you consider adding a license file for proper attribution?

**Comment by flybrianfly** [comment]
@metainf, yes, I'll add that - it'll be under an MIT license. Are you targeting Teensy? I use Docker on my computer for development, so it could be interesting if that's the case to try your solution.

**Comment by metainf** [comment]
We are targeting Teensy, its been a little tricky getting everything setup correctly with CMake + Arduino/Teensy code but I would be happy to share some details, I might put up a repo if work lets me.

The basics is downloading arduino/teensyduino, using the version to point to the URLs, and installing them in Docker.
Then patching the usb_desc.h files to add some custom USB setups(Serial,HID,MTP), and some other smaller patches (serial buffer sizes and pin strengths).
For some of the more complex libraries, like SDFat, we build as its own library, otherwise we just add the source files directly to the target.
To get around issues with different define configurations for USB setups and MCUs, we rebuild each library a target uses, just by appending something to the end of each library for each target. A better solution would probably figure out which USB setups are being used and build each library for that combination, but we don't reuse too many setups so its not an issue.

**Comment by flybrianfly** [comment]
That's interesting, I ended up making my own [Core library](https://github.com/bolderflight/core) as a modification to PJRC's library to play nice with CMake. Of course it's no longer tracking the Teensy updates, which is both a blessing and curse. Nice to easily make some modifications so the core libraries work better for us, but unfortunate that we need to manually include any bug fixes.

We also made a copy of SDFat to modify to work with CMake. Tend to keep our libraries separate and then pull them in with CMake. Mostly works well, but we do often re-use a lot of the same code from project to project (i.e. re-using sensor drivers all the time), so it is a good use-case for keeping things as libraries.

Updated to include a license file here.

**Comment by metainf** [comment]
It very much depends on how much you need to modify the core to fit, since we only make small changes, patching after downloading is easier for us. To be fair, right now the patches are just copying the files after downloading/installing. Its on our list to make actual patch files with diff.

Thanks for the license addition
